// kafka-topics-gen prints the canonical Kafka topic list derived from
// the platform-kit event taxonomy. One topic per line, sorted, no
// duplicates. Intended consumers:
//
//   - infrastructure/kafka/topics.txt is regenerated by piping this to
//     the file (see the kafka-topics make target at the repo root).
//   - The kafka-topics-init compose service reads that file at boot to
//     pre-create every topic so producers don't race auto-create on
//     first publish.
//
// Usage:
//
//	go run github.com/sentiae/platform-kit/cmd/kafka-topics-gen \
//	  > infrastructure/kafka/topics.txt
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/sentiae/platform-kit/kafka"
)

func main() {
	prefix := flag.String("prefix", "sentiae", "topic prefix")
	flag.Parse()

	for _, topic := range kafka.KnownTopics(*prefix) {
		fmt.Fprintln(os.Stdout, topic)
	}
}
